### ISSUE TITLE
ModuleNotFoundError: No module named 'datasetsforecast'

### ISSUE THREAD

**Issue by tianke0711** [Nixtla/datasetsforecast#23]
!pip install statsforecast datasetsforecast
/usr/lib/python3/dist-packages/secretstorage/dhcrypto.py:15: CryptographyDeprecationWarning: Python 3.6 is no longer supported by the Python core team. Therefore, support for it is deprecated in cryptography. The next release of cryptography (40.0) will be the last to support Python 3.6.
  from cryptography.utils import int_from_bytes
Collecting statsforecast
  Downloading statsforecast-0.5.6-py3-none-any.whl (36 kB)
ERROR: Could not find a version that satisfies the requirement datasetsforecast (from versions: none)
ERROR: No matching distribution found for datasetsforecast

**Comment by kdgutier** [comment]
Hey @tianke0711, 

This error is due to the `DatasetsForecast` library no longer supporting Python 3.6.
You can control the Python version installing the [environment.yml](https://github.com/Nixtla/datasetsforecast/blob/main/environment.yml) like this:
```
conda create -n datasetsforecast python=3.7
conda activate datasetsforecast
conda env update -f environment.yml
```
