### ISSUE TITLE
Add Forecasting Metrics

### ISSUE THREAD

**Issue by NasreddineD** [Nixtla/datasetsforecast#26]
Hi,

Is it possible to add the following metrics?
https://user-images.githubusercontent.com/87130252/248551500-5b8062c9-230f-42f9-a000-0dcfec0626c3.png

Thanks very much.

**Comment by jmoralez** [comment]
Hey. We're moving the metrics to [utilsforecast](https://github.com/Nixtla/utilsforecast). Can you please open an issue there if this is still relevant for you?
