### ISSUE TITLE
datasetsforecast no data in datasetsforecast

### ISSUE THREAD

**Issue by Sandy4321** [Nixtla/datasetsforecast#44]
something wrong in you package 

from datasetsforecast.phm2008 import PHM2008
gives error
and there is no favorita data neither

may you add data asap 
I installed  on windows 
datasetsforecast 
today using pip

**Comment by Sandy4321** [comment]
Python 3.10.11 (tags/v3.10.11:7d4cc5a, Apr  5 2023, 00:38:17) [MSC v.1929 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> from datasetsforecast.phm2008 import PHM2008
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'datasetsforecast.phm2008'

**Comment by Sandy4321** [comment]
https://nixtlaverse.nixtla.io/datasetsforecast/favorita.html#favorita-usage-example
>>> from datasetsforecast.favorita import FavoritaData
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'datasetsforecast.favorita'

**Comment by Sandy4321** [comment]
can you add data asap pls

**Comment by Sandy4321** [comment]
can you add data asap pls

**Comment by jmoralez** [comment]
These are available in the 1.0.0 release. If you upgrade the package you should able to use them, feel free to reopen otherwise.

**Comment by Sandy4321** [comment]
can you share code how to test how each data set is downloaded and save data to pkl file
I get error
Python 3.10.11 (tags/v3.10.11:7d4cc5a, Apr  5 2023, 00:38:17) [MSC v.1929 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> from datasetsforecast.phm2008 import PHM2008
>>> from datasetsforecast.M5 import M5
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'datasetsforecast.M5'

**Comment by jmoralez** [comment]
the module name is lowercase, i.e. `from datasetsforecast.m5 import M5`
